package clobclient

import (
	"context"
	"encoding/hex"
	"math/big"
	"strings"
	"testing"

	"github.com/ethereum/go-ethereum/common"
	"github.com/ethereum/go-ethereum/crypto"
)

// Polymarket POLY_1271 (deposit wallet, signature type 3) wrap signature reference vector.
// Generated by the TS reference port at tmp/polymarket-verify/poly1271.mjs against viem v2
// signing with private key 0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80
// (Hardhat account #0 = 0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266).
//
// If this fixture has to be regenerated, run the script and update both Go test and TS source
// in lockstep — the wrap format change would otherwise silently produce signatures rejected on-chain.
const (
	poly1271TestEOA           = "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266"
	poly1271TestPrivateKey    = "ac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80"
	poly1271TestDepositWallet = "0xdf8b9E8f9AB23f261F6e1B171B7454ae6E46Ba76"
	poly1271TestExchange      = "0xE111180000d2663C0091e4f400237545B87B996B"

	poly1271TestExpectedSignature = "0x6dfd2726c8108a53252040ec75addd9cebe303900ab3da745320c2363d66454054877fd862f7821de5cad11568a45d4c9247648686478ab92d3d6f772d5f3b211c3264e159346253e26a64e00b69032db0e7d32f94628de3e6eecb50304d7af3d25340ee6d5af6e00116368a85f0a404c173b86dd54e8129c2f1276aff03e270e44f726465722875696e743235362073616c742c61646472657373206d616b65722c61646472657373207369676e65722c75696e7432353620746f6b656e49642c75696e74323536206d616b6572416d6f756e742c75696e743235362074616b6572416d6f756e742c75696e743820736964652c75696e7438207369676e6174757265547970652c75696e743235362074696d657374616d702c62797465733332206d657461646174612c62797465733332206275696c6465722900ba"
)

func TestSignOrderV2Poly1271MatchesTSReference(t *testing.T) {
	t.Parallel()

	signer, err := NewPrivateKeySigner(poly1271TestPrivateKey)
	if err != nil {
		t.Fatalf("NewPrivateKeySigner() error = %v", err)
	}
	if signer.Address() != poly1271TestEOA {
		t.Fatalf("signer address = %q, want %q", signer.Address(), poly1271TestEOA)
	}

	client, err := NewClient(ClientConfig{
		ChainID:       137,
		Signer:        signer,
		SignatureType: SignatureTypePoly1271,
		FunderAddress: poly1271TestDepositWallet,
	})
	if err != nil {
		t.Fatalf("NewClient() error = %v", err)
	}

	order := OrderV2{
		Salt:          "12345",
		Maker:         poly1271TestDepositWallet,
		Signer:        poly1271TestDepositWallet,
		TokenID:       "123",
		MakerAmount:   "10520000",
		TakerAmount:   "21040000",
		Side:          SideBuy,
		SignatureType: SignatureTypePoly1271,
		Timestamp:     "1700000000000",
		Expiration:    "0",
		Metadata:      ZeroBytes32,
		Builder:       ZeroBytes32,
	}

	signed, err := client.SignOrderV2(context.Background(), order, SignOrderV2Options{})
	if err != nil {
		t.Fatalf("SignOrderV2() error = %v", err)
	}

	if signed.Signature != poly1271TestExpectedSignature {
		t.Fatalf("POLY_1271 wrapped signature mismatch\n got: %s\nwant: %s", signed.Signature, poly1271TestExpectedSignature)
	}
}

func TestSignOrderV2Poly1271RejectsMismatchedMakerSigner(t *testing.T) {
	t.Parallel()

	signer, err := NewPrivateKeySigner(poly1271TestPrivateKey)
	if err != nil {
		t.Fatalf("NewPrivateKeySigner() error = %v", err)
	}
	client, err := NewClient(ClientConfig{
		ChainID:       137,
		Signer:        signer,
		SignatureType: SignatureTypePoly1271,
		FunderAddress: poly1271TestDepositWallet,
	})
	if err != nil {
		t.Fatalf("NewClient() error = %v", err)
	}

	order := OrderV2{
		Salt:          "12345",
		Maker:         poly1271TestDepositWallet,
		Signer:        poly1271TestEOA, // wrong: should equal Maker
		TokenID:       "123",
		MakerAmount:   "10520000",
		TakerAmount:   "21040000",
		Side:          SideBuy,
		SignatureType: SignatureTypePoly1271,
		Timestamp:     "1700000000000",
		Expiration:    "0",
		Metadata:      ZeroBytes32,
		Builder:       ZeroBytes32,
	}

	if _, err := client.SignOrderV2(context.Background(), order, SignOrderV2Options{}); err == nil {
		t.Fatal("expected error when maker/signer disagree on POLY_1271 order")
	}
}

func TestCreateOrderPoly1271AutoDerivesDepositWallet(t *testing.T) {
	t.Parallel()

	signer, err := NewPrivateKeySigner(poly1271TestPrivateKey)
	if err != nil {
		t.Fatalf("NewPrivateKeySigner() error = %v", err)
	}
	client, err := NewClient(ClientConfig{
		ChainID:       137,
		Signer:        signer,
		SignatureType: SignatureTypePoly1271,
		// FunderAddress intentionally omitted — expect CREATE2 derivation.
	})
	if err != nil {
		t.Fatalf("NewClient() error = %v", err)
	}

	signedOrder, err := client.CreateOrder(context.Background(), CreateOrderParams{
		TokenID:  "123",
		Price:    "0.5",
		Size:     "21.04",
		Side:     SideBuy,
		TickSize: TickSizeTenth,
	})
	if err != nil {
		t.Fatalf("CreateOrder() error = %v", err)
	}

	if signedOrder.Maker != poly1271TestDepositWallet {
		t.Fatalf("Maker = %q, want %q (deposit wallet derived from EOA)", signedOrder.Maker, poly1271TestDepositWallet)
	}
	if signedOrder.Signer != poly1271TestDepositWallet {
		t.Fatalf("Signer = %q, want %q (POLY_1271 sets order.signer to wallet)", signedOrder.Signer, poly1271TestDepositWallet)
	}
	if signedOrder.SignatureType != SignatureTypePoly1271 {
		t.Fatalf("SignatureType = %d, want %d", signedOrder.SignatureType, SignatureTypePoly1271)
	}

	// Wrapped sig structure check: 65 + 32 + 32 + 186 + 2 = 317 bytes (634 hex chars + "0x").
	if len(signedOrder.Signature) != 2+317*2 {
		t.Fatalf("wrapped signature length = %d, want %d", len(signedOrder.Signature), 2+317*2)
	}
}

func TestClientDepositWalletAddress(t *testing.T) {
	t.Parallel()

	signer, err := NewPrivateKeySigner(poly1271TestPrivateKey)
	if err != nil {
		t.Fatalf("NewPrivateKeySigner() error = %v", err)
	}

	// Without explicit FunderAddress — derives via CREATE2.
	derivedClient, err := NewClient(ClientConfig{
		ChainID:       137,
		Signer:        signer,
		SignatureType: SignatureTypePoly1271,
	})
	if err != nil {
		t.Fatalf("NewClient() error = %v", err)
	}
	got, err := derivedClient.DepositWalletAddress()
	if err != nil {
		t.Fatalf("DepositWalletAddress() error = %v", err)
	}
	if got != poly1271TestDepositWallet {
		t.Fatalf("derived deposit wallet = %q, want %q", got, poly1271TestDepositWallet)
	}

	// Explicit FunderAddress that matches the derived wallet is accepted.
	matchingClient, err := NewClient(ClientConfig{
		ChainID:       137,
		Signer:        signer,
		SignatureType: SignatureTypePoly1271,
		FunderAddress: poly1271TestDepositWallet,
	})
	if err != nil {
		t.Fatalf("NewClient() error = %v", err)
	}
	got, err = matchingClient.DepositWalletAddress()
	if err != nil {
		t.Fatalf("DepositWalletAddress() error = %v", err)
	}
	if got != poly1271TestDepositWallet {
		t.Fatalf("matching deposit wallet = %q, want %q", got, poly1271TestDepositWallet)
	}

	// For non-POLY_1271 (e.g. proxy/safe), DepositWalletAddress still returns the configured
	// FunderAddress verbatim because legacy wallets use the same field.
	legacyClient, err := NewClient(ClientConfig{
		ChainID:       137,
		Signer:        signer,
		SignatureType: SignatureTypePolyGnosisSafe,
		FunderAddress: "0x1111111111111111111111111111111111111111",
	})
	if err != nil {
		t.Fatalf("NewClient() error = %v", err)
	}
	got, err = legacyClient.DepositWalletAddress()
	if err != nil {
		t.Fatalf("DepositWalletAddress() error = %v", err)
	}
	if got != "0x1111111111111111111111111111111111111111" {
		t.Fatalf("legacy funder address = %q, want explicit", got)
	}
}

func TestDiscoverFunderPoly1271ShortCircuits(t *testing.T) {
	t.Parallel()

	signer, err := NewPrivateKeySigner(poly1271TestPrivateKey)
	if err != nil {
		t.Fatalf("NewPrivateKeySigner() error = %v", err)
	}
	client, err := NewClient(ClientConfig{
		ChainID:       137,
		Signer:        signer,
		SignatureType: SignatureTypePoly1271,
	})
	if err != nil {
		t.Fatalf("NewClient() error = %v", err)
	}

	result, err := client.DiscoverFunder(context.Background(), FunderDiscoveryParams{})
	if err != nil {
		t.Fatalf("DiscoverFunder() error = %v", err)
	}
	if result.Preferred == nil {
		t.Fatal("expected Preferred candidate for POLY_1271 discovery")
	}
	if result.Preferred.Address != poly1271TestDepositWallet {
		t.Fatalf("preferred candidate = %q, want %q", result.Preferred.Address, poly1271TestDepositWallet)
	}
	if result.Preferred.Source != FunderCandidateSourceDepositWalletDerivation {
		t.Fatalf("preferred source = %q, want %q", result.Preferred.Source, FunderCandidateSourceDepositWalletDerivation)
	}
}

// TestSignOrderV2Poly1271RejectsForeignDepositWallet 防御 SignOrderV2 直接调用绕过 resolveOrderMaker 的场景：
// 即使 maker == signer 字段一致，maker 也必须等于 EOA 派生出的 deposit wallet，否则上链会拒签。
func TestSignOrderV2Poly1271RejectsForeignDepositWallet(t *testing.T) {
	t.Parallel()

	signer, err := NewPrivateKeySigner(poly1271TestPrivateKey)
	if err != nil {
		t.Fatalf("NewPrivateKeySigner() error = %v", err)
	}
	// 用 Hardhat #1 派生出的 deposit wallet（属于另一个 EOA），但 client 仍用 Hardhat #0 签名。
	foreign := "0x5F4f45aBd6e86C60B3Df2a4aF103f85256A2Ce6d"
	client, err := NewClient(ClientConfig{
		ChainID:       137,
		Signer:        signer,
		SignatureType: SignatureTypePoly1271,
		FunderAddress: foreign,
	})
	if err != nil {
		t.Fatalf("NewClient() error = %v", err)
	}

	order := OrderV2{
		Salt:          "12345",
		Maker:         foreign,
		Signer:        foreign,
		TokenID:       "123",
		MakerAmount:   "10520000",
		TakerAmount:   "21040000",
		Side:          SideBuy,
		SignatureType: SignatureTypePoly1271,
		Timestamp:     "1700000000000",
		Expiration:    "0",
		Metadata:      ZeroBytes32,
		Builder:       ZeroBytes32,
	}

	_, err = client.SignOrderV2(context.Background(), order, SignOrderV2Options{})
	if err == nil {
		t.Fatal("expected error when POLY_1271 maker is not derived from EOA")
	}
	if !strings.Contains(err.Error(), "does not match deposit wallet derived from signer") {
		t.Fatalf("unexpected error: %v", err)
	}
}

func TestDepositWalletAddressRejectsMisconfiguredFunder(t *testing.T) {
	t.Parallel()

	signer, err := NewPrivateKeySigner(poly1271TestPrivateKey)
	if err != nil {
		t.Fatalf("NewPrivateKeySigner() error = %v", err)
	}
	// 用户错把 EOA 当 deposit wallet 配进 FunderAddress。
	client, err := NewClient(ClientConfig{
		ChainID:       137,
		Signer:        signer,
		SignatureType: SignatureTypePoly1271,
		FunderAddress: poly1271TestEOA,
	})
	if err != nil {
		t.Fatalf("NewClient() error = %v", err)
	}

	_, err = client.DepositWalletAddress()
	if err == nil {
		t.Fatal("expected error when FunderAddress is not the derived deposit wallet for POLY_1271")
	}
	if !strings.Contains(err.Error(), "does not match deposit wallet derived from signer") {
		t.Fatalf("unexpected error: %v", err)
	}
}

// TestOrderTypeStringMatchesCTFExchangeV2OrderType 防止 orderTypeString 与 ctfExchangeV2OrderType 漂移。
// 字段任一改动都会导致 ORDER_TYPE_HASH 与 wrap 尾部字节串失配，链上 isValidSignature 静默拒签。
func TestOrderTypeStringMatchesCTFExchangeV2OrderType(t *testing.T) {
	t.Parallel()

	var b strings.Builder
	b.WriteString("Order(")
	for i, f := range ctfExchangeV2OrderType() {
		if i > 0 {
			b.WriteByte(',')
		}
		b.WriteString(f.Type)
		b.WriteByte(' ')
		b.WriteString(f.Name)
	}
	b.WriteByte(')')

	got := b.String()
	if got != orderTypeString {
		t.Fatalf("orderTypeString out of sync with ctfExchangeV2OrderType:\n got: %s\nwant: %s", orderTypeString, got)
	}
}

// TestAppDomainSepMatchesManualKeccak 是 HashStruct 的纵深防御：
// 把 typedData.HashStruct("EIP712Domain", ...) 与手算的 keccak(abi.encode(...))
// 比对，确保 geth 实现与 viem/Solidity 编码完全一致。
func TestAppDomainSepMatchesManualKeccak(t *testing.T) {
	t.Parallel()

	const chainID int64 = 137
	exchangeAddress := poly1271TestExchange

	signer, err := NewPrivateKeySigner(poly1271TestPrivateKey)
	if err != nil {
		t.Fatalf("NewPrivateKeySigner() error = %v", err)
	}
	_ = signer

	order := OrderV2{
		Salt:          "12345",
		Maker:         poly1271TestDepositWallet,
		Signer:        poly1271TestDepositWallet,
		TokenID:       "123",
		MakerAmount:   "10520000",
		TakerAmount:   "21040000",
		Side:          SideBuy,
		SignatureType: SignatureTypePoly1271,
		Timestamp:     "1700000000000",
		Expiration:    "0",
		Metadata:      ZeroBytes32,
		Builder:       ZeroBytes32,
	}

	typedData, err := buildPoly1271TypedData(order, chainID, exchangeAddress)
	if err != nil {
		t.Fatalf("buildPoly1271TypedData() error = %v", err)
	}

	gethSep, err := typedData.HashStruct("EIP712Domain", typedData.Domain.Map())
	if err != nil {
		t.Fatalf("HashStruct(EIP712Domain) error = %v", err)
	}

	// keccak256(abi.encode(DOMAIN_TYPE_HASH, keccak(name), keccak(version), chainId, verifyingContract))
	domainTypeHash := crypto.Keccak256([]byte("EIP712Domain(string name,string version,uint256 chainId,address verifyingContract)"))
	nameHash := crypto.Keccak256([]byte(ctfExchangeDomainName))
	versionHash := crypto.Keccak256([]byte(ctfExchangeV2DomainVersion))

	encoded := make([]byte, 0, 5*32)
	encoded = append(encoded, domainTypeHash...)
	encoded = append(encoded, nameHash...)
	encoded = append(encoded, versionHash...)
	encoded = append(encoded, leftPad32(big.NewInt(chainID).Bytes())...)
	encoded = append(encoded, leftPad32(common.HexToAddress(exchangeAddress).Bytes())...)
	manual := crypto.Keccak256(encoded)

	if hex.EncodeToString(gethSep) != hex.EncodeToString(manual) {
		t.Fatalf("appDomainSep mismatch:\ngeth:   %s\nmanual: %s", hex.EncodeToString(gethSep), hex.EncodeToString(manual))
	}
}

// leftPad32 pads to 32 bytes, left side.
func leftPad32(b []byte) []byte {
	if len(b) >= 32 {
		return b[len(b)-32:]
	}
	out := make([]byte, 32)
	copy(out[32-len(b):], b)
	return out
}
